// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsNnAIRR4s0Pws_htDuklA-eu0brYhuEU',
    appId: '1:900335431865:web:6a95d5011d8270d857eb68',
    messagingSenderId: '900335431865',
    projectId: 'health-sphere-55222',
    authDomain: 'health-sphere-55222.firebaseapp.com',
    databaseURL: 'https://health-sphere-55222-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-sphere-55222.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYV10cK2UK7IRXAjx1C4Wra9QFqJk2K5A',
    appId: '1:900335431865:android:a92f94a6617c12ca57eb68',
    messagingSenderId: '900335431865',
    projectId: 'health-sphere-55222',
    databaseURL: 'https://health-sphere-55222-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-sphere-55222.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFDMk8ZlMqcUqMETDYh2tlDvyfbuO84RQ',
    appId: '1:900335431865:ios:4e6435c2184a982157eb68',
    messagingSenderId: '900335431865',
    projectId: 'health-sphere-55222',
    databaseURL: 'https://health-sphere-55222-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-sphere-55222.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFDMk8ZlMqcUqMETDYh2tlDvyfbuO84RQ',
    appId: '1:900335431865:ios:4e6435c2184a982157eb68',
    messagingSenderId: '900335431865',
    projectId: 'health-sphere-55222',
    databaseURL: 'https://health-sphere-55222-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-sphere-55222.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsNnAIRR4s0Pws_htDuklA-eu0brYhuEU',
    appId: '1:900335431865:web:bc0774fb25a7002557eb68',
    messagingSenderId: '900335431865',
    projectId: 'health-sphere-55222',
    authDomain: 'health-sphere-55222.firebaseapp.com',
    databaseURL: 'https://health-sphere-55222-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'health-sphere-55222.firebasestorage.app',
  );
}
